theme: jekyll-theme-minimal
title: Octocat's homepage
description: Bookmark this to keep an eye on my project updates!
domain: my-site.github.io       # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://lucaswang0.github.io  # the base hostname and protocol for your site, e.g. http://example.com
baseurl: /blog/      # place folder name if the site is served in a subfolder
